# La configuration Netlify est cassée et l'hebergeur ne fournit les bons
# certificats pour le site en production. Pour essayer de contourner le problème
# on créer un nouveau "site" qui se contente de faire une redirection
# transparante.



[[redirects]]
  from = "https://mon-entreprise.fr/modules/v2/dist/simulateur.js"
  to = "https://mon-entreprise.urssaf.fr/simulateur-iframe-integration.js"
  status = 301

[[redirects]]
  from = "https://mon-entreprise.fr/dist/simulateur.js"
  to = "https://mon-entreprise.urssaf.fr/simulateur-iframe-integration.js"
  status = 301

[[redirects]]
  from = "https://mon-entreprise.fr/*"
  to = "https://mon-entreprise.urssaf.fr/:splat"
  status = 301
  
[[redirects]]
  from = "https://mycompanyinfrance.fr/*"
  to = "https://mycompanyinfrance.urssaf.fr/:splat"
  status = 301
  
