# La configuration Netlify est cassée et l'hebergeur ne fournit les bons
# certificats pour le site en production. Pour essayer de contourner le problème
# on créer un nouveau "site" qui se contente de faire une redirection
# transparante.



[[redirects]]
  from = "https://mon-entreprise.fr/modules/v2/dist/simulateur.js"
  to = "https://2432--mon-entreprise.netlify.app/simulateur-iframe-integration.js"
  status = 301

[[redirects]]
  from = "https://mon-entreprise.fr/dist/simulateur.js"
  to = "https://2432--mon-entreprise.netlify.app/simulateur-iframe-integration.js"
  status = 301

[[redirects]]
  from = "https://mon-entreprise.fr/*"
  to = "https://2432--mon-entreprise.netlify.app/:splat"
  status = 301
  
[[redirects]]
  from = "https://mycompanyinfrance.fr/*"
  to = "https://2432--mon-entreprise.netlify.app/:splat"
  status = 301
  
[[redirects]]
  from = "https://mycompanyinfrance.urssaf.fr/*"
  to = "https://2432--mon-entreprise.netlify.app/:splat"
  status = 200
  
[[redirects]]
  from = "https://mon-entreprise.urssaf.fr/*"
  to = "https://2432--mon-entreprise.netlify.app/:splat"
  status = 200
  
